"""added resultDesc field

Revision ID: 42847537d4d3
Revises: 3f3d4eceedab
Create Date: 2022-03-04 07:58:19.658792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42847537d4d3'
down_revision = '3f3d4eceedab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_dump', sa.Column('resultDesc', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_dump', 'resultDesc')
    # ### end Alembic commands ###
