version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev