@host=e3ad-105-163-45-146.ngrok.io 



# @name test_stk_endpoint
POST http://{{host}}/stk/
Host:{{host}}
Content-Type: application/json

{
    "phone": "0792066199",
    "amount": "1",
    "shortcode": "174379",
    "AccountReference": "Boots Kenya"
}
###

# @name test_callback_url

POST https://{{host}}/stk/callback
Host:{{host}}
Content-Type: application/json

{
    "phone": "0792066199",
    "amount": "1"
}
###