@host=992b-102-166-146-10.ngrok.io

//test_stk_endpoint

###
POST http://{{host}}/stk/
Host:{{host}}
Content-Type: application/json

{
    "phone": "0792066199",
    "amount": "1",
    "shortcode": "174379",
    "AccountReference": "Boots Kenya",
    "ApplicationId": "0001"
}
###

//test_callback_url

POST https://{{host}}/stk/callback
Host:{{host}}
Content-Type: application/json

{
    "phone": "0792066199",
    "amount": "1"
}
###

//get all transactions:

GET http://{{host}}/stk/fetchAllTransactions 
Host:{{host}}

###

//test_callback_url

POST http://{{host}}/stk/checkStatus
Host:{{host}}
Content-Type: application/json

{
    "CheckoutRequestID": "ws_CO_020320220739058841",
    "shortcode": "174379"
}
###


//delete all transactions:

GET http://{{host}}/stk/deleteAllTransactions 
Host:{{host}}

###