@host=localhost:5000

//test_stk_endpoint

###
POST https://{{host}}/stk/
Host:{{host}}
Content-Type: application/json

{
    "phone": "0701577567",
    "amount": "1",
    "shortcode": "174379",
    "AccountReference": "Boots Kenya",
    "ApplicationId": "0001"
}
###

//test_callback_url

POST https://{{host}}/stk/callback
Host:{{host}}
Content-Type: application/json

{"Body":
{"stkCallback":
{"MerchantRequestID": "22691-74557427-1",
  "CheckoutRequestID": "ws_CO_050320221821477511",
  "ResultCode": 1032,
  "ResultDesc": "Request cancelled by user"
}
}
}
###

//get all transactions:

GET http://{{host}}/stk/fetchAllTransactions 
Host:{{host}}

###

//check transaction status:

POST http://{{host}}/stk/checkStatus
Host:{{host}}
Content-Type: application/json

{
    "CheckoutRequestID": "ws_CO_09092022161825487792066199",
    "shortcode": "174379",
    "ApplicationId": "0001"
}
###


//delete all transactions:

GET http://{{host}}/stk/deleteAllTransactions 
Host:{{host}}

###

//test reversals endpoint:

POST http://{{host}}/reversals/
Host:{{host}}
Content-Type: application/json

{
  "TransactionID": "QI167HYZNU",
  "shortcode": "174379",
  "ApplicationId": "0001",
  "amount": "1"
}
###

//test account balance endpoint:

POST http://{{host}}/accBal/
Host:{{host}}
Content-Type: application/json

{
  "shortcode": "174379",
  "ApplicationId": "0001"
}
###