"""Initial Migrations

Revision ID: 2057d827e526
Revises: 
Create Date: 2022-02-06 14:30:48.750054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2057d827e526'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'request_dump', ['uuid_'])
    op.add_column('response_dump', sa.Column('service', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'response_dump', ['uuid_'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response_dump', type_='unique')
    op.drop_column('response_dump', 'service')
    op.drop_constraint(None, 'request_dump', type_='unique')
    # ### end Alembic commands ###
