"""null error resolved

Revision ID: 3f3d4eceedab
Revises: fc03ba26ac47
Create Date: 2022-02-24 08:04:52.355730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3d4eceedab'
down_revision = 'fc03ba26ac47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_dump', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('request_dump', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('request_dump', 'shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('request_dump', 'accountReference',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('request_dump', 'requestStatus',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('request_dump', 'serviceStatus',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('request_dump', 'accountBalance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('request_dump', 'appId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('request_dump', 'errorMessage',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_dump', 'errorMessage',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('request_dump', 'appId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_dump', 'accountBalance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_dump', 'serviceStatus',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('request_dump', 'requestStatus',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('request_dump', 'accountReference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('request_dump', 'shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('request_dump', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('request_dump', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
