"""changed stk model name

Revision ID: 29683d8f06be
Revises: bbd05989d925
Create Date: 2022-03-05 20:25:05.745174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29683d8f06be'
down_revision = 'bbd05989d925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_dump')
    op.create_unique_constraint(None, 'stk_request_dump', ['uuid_'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stk_request_dump', type_='unique')
    op.create_table('request_dump',
    sa.Column('uuid_', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('shortcode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('accountReference', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('appId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requestStatus', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('serviceStatus', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('checkoutRequestId', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('merchantRequestId', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('mpesaReceiptNumber', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('accountBalance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('errorMessage', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resultDesc', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid_', name='request_dump_pkey'),
    sa.UniqueConstraint('uuid_', name='request_dump_uuid__key')
    )
    # ### end Alembic commands ###
