"""extracted request dump items

Revision ID: f10399467f45
Revises: 2057d827e526
Create Date: 2022-02-22 07:49:55.668826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f10399467f45'
down_revision = '2057d827e526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_dump', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('request_dump', sa.Column('phone', sa.String(length=12), nullable=False))
    op.add_column('request_dump', sa.Column('shortcode', sa.String(length=20), nullable=False))
    op.add_column('request_dump', sa.Column('accountReference', sa.String(length=50), nullable=False))
    op.add_column('request_dump', sa.Column('appId', sa.Integer(), nullable=False))
    op.drop_column('request_dump', 'payload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_dump', sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('request_dump', 'appId')
    op.drop_column('request_dump', 'accountReference')
    op.drop_column('request_dump', 'shortcode')
    op.drop_column('request_dump', 'phone')
    op.drop_column('request_dump', 'amount')
    # ### end Alembic commands ###
