"""store more data on the request status for audit and IDs for cross-referencing during reconciliation

Revision ID: fc03ba26ac47
Revises: f10399467f45
Create Date: 2022-02-24 07:47:52.120127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc03ba26ac47'
down_revision = 'f10399467f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_dump', sa.Column('requestStatus', sa.Boolean(), nullable=True))
    op.add_column('request_dump', sa.Column('serviceStatus', sa.Boolean(), nullable=True))
    op.add_column('request_dump', sa.Column('checkoutRequestId', sa.String(length=30), nullable=True))
    op.add_column('request_dump', sa.Column('merchantRequestId', sa.String(length=30), nullable=True))
    op.add_column('request_dump', sa.Column('mpesaReceiptNumber', sa.String(length=30), nullable=True))
    op.add_column('request_dump', sa.Column('accountBalance', sa.Integer(), nullable=True))
    op.add_column('request_dump', sa.Column('updated_at', sa.String(length=50), nullable=True))
    op.add_column('request_dump', sa.Column('errorMessage', sa.String(length=100), nullable=True))
    op.alter_column('request_dump', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_dump', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('request_dump', 'shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('request_dump', 'accountReference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('request_dump', 'appId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_dump', 'appId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_dump', 'accountReference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('request_dump', 'shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('request_dump', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('request_dump', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('request_dump', 'errorMessage')
    op.drop_column('request_dump', 'updated_at')
    op.drop_column('request_dump', 'accountBalance')
    op.drop_column('request_dump', 'mpesaReceiptNumber')
    op.drop_column('request_dump', 'merchantRequestId')
    op.drop_column('request_dump', 'checkoutRequestId')
    op.drop_column('request_dump', 'serviceStatus')
    op.drop_column('request_dump', 'requestStatus')
    # ### end Alembic commands ###
